apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: uc2gdf3ke-go 
  janus-idp.io/tekton: uc2gdf3ke-go
  backstage.io/kubernetes-id: uc2gdf3ke-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uc2gdf3ke-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml