apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uc2gdf3ke-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uc2gdf3ke-go 
  name: uc2gdf3ke-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uc2gdf3ke-go 
